language: erlang
before_install: sudo apt-get install libpam0g-dev libexpat1-dev slapd
script: tools/travis-build.sh ""
services: redis-server
branches:
        only:
                - master
notifications:
        email: michalwski@gmail.com
otp_release:
        - R15B03
env:
        - TEST_CONFIG=internal_redis
        - TEST_CONFIG=internal_mnesia
        
