language: erlang
before_install: sudo apt-get install libpam0g-dev libexpat1-dev
before_script: tools/travis-setup-db.sh
script: tools/travis-build.sh password
services: redis-server
branches:
        only:
                - master
notifications:
        email: michalwski@gmail.com
otp_release:
        - R15B03
env:
        - TEST_CONFIG=odbc_mnesia DB=mysql

